### ISSUE TITLE
E5113: Error while calling lua chunk: /Users/jp/.config/nvim/lua/lazy-setup.lua:2: attempt to index field 'uv' (a nil value)

### ISSUE THREAD

**Issue by okjonny** [sadikeey/nvim#1]
Hello @sadikeey,
I followed the steps for installing sadikeey/nvim (backup current config & git clone https://github.com/sadikeey/nvim.git ~/.config/nvim), but after running ```nvim``` I am met with the following error:

```
Error detected while processing /Users/jp/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/jp/.config/nvim/lua/lazy-setup.lua:2: attempt to index field 'uv' (a nil value)
stack traceback:
        /Users/jonnypalacios/.config/nvim/lua/lazy-setup.lua:2: in main chunk
        [C]: in function 'require'
        /Users/jp/.config/nvim/init.lua:3: in main chunk
```
I am currently running:
nvim: 0.9.1
node: 18.16.0
npm: 9.5.1
installed: gcc/fd/ripgrep

I'm new to nvim environment, thanks for the help

**Comment by sadiksaifi** [comment]
In the `~/.config/nvim/lua/lazy-setup` file in the second line change `vim.uv.fs_stat(lazypath)` to this `vim.loop.fs_stat(lazypath)`

Actually I have been running nvim v-0.10 dev build where `vim.loop` has been deprecated in favour of `vim.uv` and I have forget to mention in the docs but now I have updated the installing instructions.
